 -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
